trainer/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.trainers, name="trainers_page"),
    path("<int:trainer_id>/", views.trainer_detail, name="trainer_detail"),
    path("<int:trainer_id>/set_desc/", views.set_trainer_description, name="set_trainer_description"),
    path("<int:trainer_id>/set_schedule/", views.set_working_hours, name="set_working_hours"),
    path("<int:trainer_id>/service/edit/<int:service_id>/", views.edit_trainer_service, name="edit_trainer_service"),
    path("<int:trainer_id>/service/add/", views.add_trainer_service, name="add_trainer_service"),
    path("<int:trainer_id>/booking/<int:service_id>/", views.book_service, name="book_service"),
]

trainerApp/urls.py
from django.contrib import admin
from django.urls import path, include

import trainer.views
import users.views
from trainerApp import views

urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", admin.site.urls),
    path("register/", users.views.register_page, name="user_register"),
    path("login/", users.views.login_page, name="user_login"),
    path("logout/", users.views.logout_page, name="user_logout"),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("booking/", include(("booking.urls", "booking"), namespace="booking")),
    path("trainer/", include(("trainer.urls", "trainer"), namespace="trainer")),

    # for testing
    path("hot_change_group/", views.hot_change_group, name="hot_change_group"),
]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.users, name="users_page"),
    path("<int:user_id>/", views.user_details, name="user_details"),
    path("user/<int:user_id>/rate/", views.add_or_update_rating, name="add_or_update_rating"),
]

trainer/models.py
from django.contrib.auth.models import User
from django.db import models


class TrainerDescription(models.Model):
    text = models.TextField()
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)


class TrainerSchedule(models.Model):
    datetime_start = models.DateTimeField()
    datetime_end = models.DateTimeField()
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)


class Category(models.Model):
    name = models.CharField(max_length=256)


class Service(models.Model):
    LEVEL_CHOICES = [(1, "Novice"),
                     (2, "Medium"),
                     (3, "Advanced"), ]

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    trainer = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.FloatField()
    level = models.IntegerField(choices=LEVEL_CHOICES)
    duration = models.DurationField()

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Rating(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE, related_name='given_ratings')
    recipient = models.OneToOneField(User, on_delete=models.CASCADE, related_name='received_ratings')
    rate = models.IntegerField(default=0)
    text = models.CharField(max_length=512)

trainer/forms.py
from django import forms

from trainer.models import TrainerSchedule, TrainerDescription, Category, Service


class AddTrainerService(forms.ModelForm):
    class Meta:
        model = Service
        fields = ["category", "duration", "price", "level"]

    level = forms.ChoiceField(choices=Service.LEVEL_CHOICES, label="Level")

    def __init__(self, *args, **kwargs):  # redef __init__ for real-time update choices list
        super().__init__(*args, **kwargs)
        self.fields["category"].choices = [(cat.id, cat.name) for cat in Category.objects.all()]


class SetWorkingHours(forms.ModelForm):
    class Meta:
        model = TrainerSchedule
        fields = ["datetime_start", "datetime_end"]

    datetime_start = forms.DateTimeField(widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
                                         required=True)
    datetime_end = forms.DateTimeField(widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
                                       required=True)


class EditTrainerService(forms.ModelForm):
    class Meta:
        model = Service
        fields = ["category", "duration", "price", "level", "delete"]

    level = forms.ChoiceField(choices=Service.LEVEL_CHOICES, label="Level")
    delete = forms.BooleanField(required=False, label="Delete this service?")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["category"].choices = [(cat.id, cat.name) for cat in Category.objects.all()]


class SetDescription(forms.ModelForm):
    class Meta:
        model = TrainerDescription
        fields = ["text"]

users/forms.py
from django import forms
from django.contrib.auth.models import User

from users.models import Rating


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]

    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    is_trainer = forms.BooleanField(required=False, label="Check if you a trainer:")
    username = forms.CharField(help_text="")

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords doesn't match!")

        return cleaned_data


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)


class RatingAndCommentForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["rate", "text"]

    rate = forms.ChoiceField(choices=[(i, str(i)) for i in range(1, 6)],
                             widget=forms.RadioSelect,
                             required=True)
    text = forms.CharField(widget=forms.Textarea, required=False)

trainer/views.py
from django.contrib.auth.models import User, Group
from django.core.paginator import Paginator
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.utils import timezone

import trainer.models
from booking.models import Booking

from datetime import datetime, timedelta

# Create your views here.
from trainer.forms import AddTrainerService, SetWorkingHours, EditTrainerService, SetDescription


def trainers(request):
    """ Отображение всех тренеров по категориям. """
    selected_category = request.GET.get("category", "all")

    trainer_group = Group.objects.get(name="Trainer")
    trainers = User.objects.filter(groups=trainer_group)

    if selected_category != "all":
        trainers = trainers.filter(service__category__id=selected_category).distinct()

    categories = trainer.models.Category.objects.all()

    paginator = Paginator(trainers, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, "trainers.html", {"page_obj": page_obj,
                                             "categories": categories,
                                             "selected_category": selected_category})


def trainer_detail(request, trainer_id):
    """ Страница тренера: настройки сервисов, рабочего времени. """
    is_trainer = request.user.is_authenticated and request.user.groups.filter(name="Trainer").exists()
    service_categories = trainer.models.Category.objects.all()
    trainer_services = trainer.models.Service.objects.filter(trainer=trainer_id)
    trainer_data = User.objects.filter(id=trainer_id).first()
    form_add_service = AddTrainerService()
    form_set_working_hours = SetWorkingHours()
    form_set_description = SetDescription()

    if request.method == "POST":
        pass

    return render(request, "trainer.html", {"form_add_service": form_add_service,
                                            "form_set_working_hours": form_set_working_hours,
                                            "form_set_description": form_set_description,
                                            "is_trainer": is_trainer,
                                            "trainer": trainer_data,
                                            "trainer_id": trainer_id,
                                            "service_categories": service_categories,
                                            "trainer_services": trainer_services})


def book_service(request, trainer_id, service_id, day=None):
    if request.method == "GET":
        if request.user.groups.filter(name="User").exists():
            from trainer.utils import generate_actual_calendar, booking_time_discovery
            service = trainer.models.Service.objects.filter(pk=service_id).first()

            date_param = request.GET.get("date")
            if date_param:
                date = datetime.strptime(date_param, "%Y-%m-%d").date()
            else:
                now = datetime.now()
                date = now.date()

            current_month = int(request.GET.get("month", timezone.now().month))
            current_year = int(request.GET.get("year", timezone.now().year))

            min_date = timezone.now().date()
            max_date = min_date + timedelta(days=90)
            if (current_year, current_month) > (max_date.year, max_date.month):
                current_year, current_month = max_date.year, max_date.month
            if (current_year, current_month) < (min_date.year, min_date.month):
                current_year, current_month = min_date.year, min_date.month

            # Расчёт следующих месяцев и годов
            next_month = current_month + 1 if current_month < 12 else 1
            next_year = current_year if current_month < 12 else current_year + 1

            next_next_month = next_month + 1 if next_month < 12 else 1
            next_next_year = next_year if next_month < 12 else next_year + 1

            # Генерация календарей
            calendar_rows = generate_actual_calendar(current_year, current_month, date)
            next_calendar_rows = generate_actual_calendar(next_year, next_month, date)
            next_next_calendar_rows = generate_actual_calendar(next_next_year, next_next_month, date)

            possible_times = booking_time_discovery(trainer_id, service_id, date)
            if not day:
                now = datetime.now()
                day = now.date()

            return render(request, "service.html", {"service": service,
                                                    "calendar_rows": calendar_rows,
                                                    "next_calendar_rows": next_calendar_rows,
                                                    "next_next_calendar_rows": next_next_calendar_rows,
                                                    "current_month": current_month,
                                                    "current_year": current_year,
                                                    "next_month": next_month,
                                                    "next_year": next_year,
                                                    "next_next_month": next_next_month,
                                                    "next_next_year": next_next_year,
                                                    "possible_times": possible_times,
                                                    "selected_day": date})

    if request.method == "POST":
        if request.user.groups.filter(name="User").exists():
            date = request.POST.get("date")
            booking_time = request.POST.get("booking_time")

            if booking_time:
                time_start, time_end = booking_time.split("-")
            else:
                time_start = time_end = None

            user = request.user
            trainer_data = User.objects.get(id=trainer_id)
            service = trainer.models.Service.objects.get(id=service_id)

            datetime_start = datetime.combine(datetime.strptime(date, "%Y-%m-%d").date(),
                                              datetime.strptime(time_start, "%H:%M").time())
            datetime_end = datetime.combine(datetime.strptime(date, "%Y-%m-%d").date(),
                                            datetime.strptime(time_end, "%H:%M").time())

            booking = Booking.objects.create(datetime_start=datetime_start,
                                             datetime_end=datetime_end,
                                             status=True,
                                             service_id=service.id,
                                             trainer_id=trainer_data.id,
                                             user_id=user.id)

            return redirect("trainer:book_service", trainer_id=trainer_data.id, service_id=service.id)
    return HttpResponseForbidden("Forbidden")


def add_trainer_service(request, trainer_id):
    if request.method == "POST":
        if request.user.groups.filter(name="Trainer").exists():
            form = AddTrainerService(request.POST)
            if form.is_valid():
                duration = 60 * form.cleaned_data["duration"]
                service = trainer.models.Service(level=form.cleaned_data["level"],
                                                 duration=duration,
                                                 price=form.cleaned_data["price"],
                                                 category=form.cleaned_data["category"],
                                                 trainer=request.user)
                service.save()

                return redirect("trainer:trainer_detail", trainer_id=trainer_id)
        else:
            return HttpResponseForbidden


def edit_trainer_service(request, trainer_id, service_id):
    if request.method == "GET":
        if request.user.groups.filter(name="Trainer").exists():
            service = trainer.models.Service.objects.get(id=service_id, trainer=request.user)
            form = EditTrainerService(instance=service)

            return render(request, "edit_services.html", {"form": form,
                                                          "trainer_id": trainer_id,
                                                          "service_id": service_id})
    if request.method == "POST":
        if request.user.groups.filter(name="Trainer").exists():
            service = trainer.models.Service.objects.get(id=service_id,
                                                         trainer=request.user)
            form = EditTrainerService(request.POST, instance=service)
            if form.is_valid():
                form.save()
                if form.cleaned_data.get("delete"):
                    service.delete()
                return redirect("trainer:trainer_detail", trainer_id=trainer_id)

    return HttpResponseForbidden("Forbidden")


def set_working_hours(request, trainer_id):
    if request.method == "POST":
        if request.user.groups.filter(name="Trainer").exists():
            form = SetWorkingHours(request.POST)
            if form.is_valid():
                schedule = trainer.models.TrainerSchedule(datetime_start=form.cleaned_data["datetime_start"],
                                                          datetime_end=form.cleaned_data["datetime_end"],
                                                          trainer=request.user)
                schedule.save()
                return redirect("trainer:trainer_detail", trainer_id=trainer_id)
        else:
            return HttpResponseForbidden


def set_trainer_description(request, trainer_id):
    if request.method == "POST":
        if request.user.groups.filter(name="Trainer").exists():
            form = SetDescription(request.POST)
            if form.is_valid():
                description, created = trainer.models.TrainerDescription.objects.get_or_create(
                    trainer=request.user,

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}trainerAPP - index{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>

    <header>
        <h3>trainerAPP</h3>
        <nav>
            <ul>
                <li><a href="/">Home</a></li>

                {% if request.user.is_authenticated %}
                    <li><a href="/logout/">Log out</a></li>
                    <li><a href="/users/">Users</a></li>
                    <li><a href="/trainer/">Trainers</a></li>
                    <li><a href="/users/{{ request.user.id }}">My Profile</a></li>
                {% else %}
                    <li><a href="/register/">Registration</a></li>
                    <li><a href="/login/">Log in</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        *for testing*
        <p>Username: {{ request.user.username }}</p>
        {% if request.user.groups.first %}
            <p>Group: {{ request.user.groups.first.name }}</p>
            <form action="{% url 'hot_change_group' %}" method="POST">
                {% csrf_token %}
                <button type="submit">Switch Role</button>
            </form>
        {% else %}
            No group assigned
        {% endif %}

        <p>&copy; 2025 trainerAPP</p>
    </footer>
</body>
</html>

templates/calendar_table.html
<table border="1" cellspacing="0" cellpadding="5">
    <thead>
        <tr>
            <th>Mon</th>
            <th>Tue</th>
            <th>Wed</th>
            <th>Thu</th>
            <th>Fri</th>
            <th style="color: red;">Sat</th>
            <th style="color: red;">Sun</th>
        </tr>
    </thead>
    <tbody>
        {% for week in calendar_rows %}
        <tr>
            {% for day in week %}
            <td>
                {% if day.is_valid %}
                    {% if day.is_holiday %}
                        <span style="color: red;">{{ day.number }}</span>
                    {% elif day.is_unavailable %}
                        <span style="color: gray;">{{ day.number }}</span>
                    {% else %}
                        <a href="?date={{ year }}-{{ month|stringformat:"02d" }}-{{ day.number|stringformat:"02d" }}">
                            {{ day.number }}
                        </a>
                    {% endif %}
                {% endif %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/comments.html
{% if user == request.user %}
    <h3>Ratings and Comments</h3>
    <p>Number of ratings received: {{ ratings_received.count }}</p>

    <form method="GET" action="">
        <input type="hidden" name="show_my_comments" value="{% if show_my_comments %}false{% else %}true{% endif %}">
        {% if not show_my_comments %}
            <button type="submit" class="btn btn-primary">Show my comments</button>
        {% else %}
            <button type="submit" class="btn btn-primary">Show received comments</button>
        {% endif %}
    </form>

{% else %}
    {% if has_connection %}
        <h3>Leave a Rating and Comment</h3>

        <!-- Форма для оставления оценки -->
        <form method="POST" action="{% url 'users:add_or_update_rating' user_id=user.id %} ">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                {% if existing_rating %}
                    Change rating
                {% else %}
                    Submit rating
                {% endif %}
            </button>
        </form>
    {% else %}
        <p>You can only leave a rating and comment if you have a booking connection with this user.</p>
    {% endif %}
{% endif %}

<h3>All Comments</h3>
<ul>
    {% for rating in ratings_received %}
        <li>
            <strong>Rating: {{ rating.rate }} / 5</strong><br>
            <strong>Comment:</strong> {{ rating.text|default:"No comment" }}<br>
            <strong>From:</strong> <a href="{% url 'users:user_details' user_id=rating.author.id %}">
                {{ rating.author.first_name }} {{ rating.author.last_name }}
            </a><br>
        </li>
    {% empty %}
        <p>No comments yet.</p>
    {% endfor %}
</ul>

templates/edit_services.html
{% extends "base.html" %}

{% block title %}Service Edit Page{% endblock %}

{% block content %}

        <form method="POST" action="{% url 'trainer:edit_trainer_service' trainer_id=trainer_id service_id=service_id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Home - My Site (index page){% endblock %}

{% block content %}

        {% if error %}
            <p class="message error">{{ error }}</p>
        {% endif %}

        {% if success %}
            <p class="message success">{{ success }}</p>
        {% endif %}

        {% if warning %}
            <p class="message warning">{{ warning }}</p>
        {% endif %}

    <h2>Welcome to the homepage!</h2>
    <p>This is the content of the homepage.</p>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Log in{% endblock %}

{% block content %}

    <h2>Log in</h2>

    <form action="{% url "user_login" %}" method="POST">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="error">
                {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

    <h2>Register</h2>

    <form action="{% url 'user_register' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>

{% endblock %}

templates/trainer.html
{% extends "base.html" %}

{% block title %}Trainer{% endblock %}

{% block content %}

    {% if trainer_id == request.user.id %}
        <h2>My Services</h2>
    {% else %}
        <h2><a href="{% url 'users:user_details' user_id=trainer_id %}">{{ trainer.first_name }} {{ trainer.last_name }}</a> Services</h2>
    {% endif %}

        {% for service in trainer_services %}
            <br>Category: {{ service.category.name }}
            <br>Price: {{ service.price }} USD
            <br>Duration: {{ service.duration }}
            <br>Level: {{ service.level }}
                {% if trainer_id == request.user.id %}
                    <br><a href="{% url 'trainer:edit_trainer_service' trainer_id=trainer_id  service_id=service.id%}">...Edit</a>
                {% endif %}
                {% if not is_trainer %}
                    <br><a href="{% url 'trainer:book_service' trainer_id=trainer_id service_id=service.id %}">Book</a>
                {% endif %}
            <br>-------------------------
        {% endfor %}

    {% if is_trainer %}
        <form action="{% url 'trainer:add_trainer_service' trainer_id=trainer_id %}" method="POST">
            <h2>Add New Service</h2>
            {% csrf_token %}
            {{ form_add_service.as_p }}
            <button type="submit">Submit</button>
        </form>


        <form action="{% url 'trainer:set_working_hours' trainer_id=trainer_id %}" method="POST">
            <h2>Set Working Hours</h2>
            {% csrf_token %}
            {{ form_set_working_hours.as_p }}
            <button type="submit">Submit</button>
        </form>


        <form action="{% url 'trainer:set_trainer_description' trainer_id=trainer_id %}" method="POST">
            <h2>Set My Description</h2>
            {% csrf_token %}
            {{ form_set_description.as_p }}
            <button type="submit">Submit</button>
        </form>
    {% endif %}
{% endblock %}

templates/trainers.html
{% extends "base.html" %}

{% block title %}All Trainers{% endblock %}

{% block content %}

    <h2>All Trainers</h2>

    <form method="get">
        <label for="category">Filter by category:</label>
        <select name="category" id="category" onchange="this.form.submit()">
            <option value="all" {% if not selected_category or selected_category == 'all' %}selected{% endif %}>All categories</option>
            {% for category in categories %}
                <option value="{{ category.id }}" {% if selected_category|default:'' == category.id|stringformat:"s" %}selected{% endif %}>
                    {{ category.name }}
                </option>
            {% endfor %}
        </select>
    </form>

    {% if page_obj %}
        {% for trainer in page_obj %}
            <p>
                <a href="{% url 'trainer:trainer_detail' trainer.id %}">{{ trainer.first_name }} {{ trainer.last_name }}</a>
            </p>
        {% endfor %}
    {% else %}
        <p>No trainers found.</p>
    {% endif %}

    <!-- Pagination -->
    <div>
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1{% if selected_category %}&category={{ selected_category }}{% endif %}">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}{% if selected_category %}&category={{ selected_category }}{% endif %}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock %}

templates/user_page.html
{% extends "base.html" %}

{% block title %}{{ user.first_name }} {{ user.last_name }} page{% endblock %}

{% block content %}
    <h2>{{ user.first_name }} {{ user.last_name }} profile</h2>
    {% if user == request.user %}
        <br>User ID: {{ user.id }}
        <br>Username: {{ user.username }}
    {% endif %}
    <br>First Name: {{ user.first_name }}
    <br>Last Name: {{ user.last_name }}
    {% if user == request.user %}
        <br>Email: {{ user.email }}
    {% endif %}
    <br>Register Date: {{ user.date_joined }}

    {% if trainer_description %}
        <br><br>About trainer: {{ trainer_description.text }}
    {% endif %}

    {% if trainer_services_exists %}
        <br><br><a href="{% url 'trainer:trainer_detail' user.id %}">To {{ user.first_name }} {{ user.last_name }} Services</a>
    {% endif %}

    {% if user == request.user %}
        <br><br><h2>Booked Services</h2>

        <h3>Upcoming Bookings</h3>
        {% if future_bookings %}
            <ul>
                {% for booking in future_bookings %}
                    <li>
                        <strong>Date:</strong> {{ booking.datetime_start|date:"Y-m-d H:i" }}<br>
                        <strong>Duration:</strong> {{ booking.service.duration }}<br>
                        {% if trainer_services_exists %}
                            <strong>Client:</strong>
                            <a href="{% url 'users:user_details' user_id=booking.user.id %}">
                                {{ booking.user.first_name }} {{ booking.user.last_name }}
                            </a>
                        {% else %}
                            <strong>Trainer:</strong>
                            <a href="{% url 'trainer:trainer_detail' trainer_id=booking.service.trainer_id %}">
                                {{ booking.service.trainer.first_name }} {{ booking.service.trainer.last_name }}
                            </a>
                        {% endif %}

                        {% if booking.status == False %}
                            <br><span style="color: red; font-weight: bold;">Cancelled</span>
                        {% else %}
                            <!-- Форма для отмены бронирования -->
                            <form method="POST" action="">
                                {% csrf_token %}
                                <input type="hidden" name="booking_id" value="{{ booking.id }}">
                                <button type="submit" class="btn btn-danger">Cancel Booking</button>
                            </form>
                        {% endif %}
                    </li>
                    <br>
                {% endfor %}
            </ul>
        {% else %}
            <p>No upcoming bookings.</p>
        {% endif %}

        <hr>

        <h3>Past Bookings</h3>
        {% if past_bookings %}
            <ul>
                {% for booking in past_bookings %}
                    <li>
                        <strong>Date:</strong> {{ booking.datetime_start|date:"Y-m-d H:i" }}<br>
                        <strong>Duration:</strong> {{ booking.service.duration }}<br>
                        {% if trainer_services_exists %}
                            <strong>Client:</strong>
                            <a href="{% url 'users:user_details' user_id=booking.user.id %}">
                                {{ booking.user.first_name }} {{ booking.user.last_name }}
                            </a>
                        {% else %}
                            <strong>Trainer:</strong>
                            <a href="{% url 'trainer:trainer_detail' trainer_id=booking.service.trainer_id %}">
                                {{ booking.service.trainer.first_name }} {{ booking.service.trainer.last_name }}
                            </a>
                        {% endif %}
                        {% if booking.status == False %}
                            <br><span style="color: red; font-weight: bold;">Cancelled</span>
                        {% endif %}
                    </li>
                    <br>
                {% endfor %}
            </ul>
        {% else %}
            <p>No past bookings.</p>
        {% endif %}
    {% endif %}

    <!-- Ссылка на раздел для оценок и комментариев -->
    {% include 'comments.html' %}

{% endblock %}

templates/users.html
{% extends "base.html" %}

{% block title %}All users page{% endblock %}

{% block content %}

    <h2>All users page</h2>

    {% for user in page_obj %}
        <p><a href="{% url 'users:user_details' user.id %}">{{ user.first_name }} {{ user.last_name }}</a></p>
    {% endfor %}

    <!-- Pagination -->
    <div>
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>


{% endblock %}